In [2]:
import numpy as np

In [2]:
##Create a numpy array 
a=np.array([(1,2,3),(2,3,4)])

In [3]:
a.size

6

In [4]:
a.shape

(2, 3)

In [6]:
a.sum()

15

In [7]:
## Create a array of Zeros 

b=np.zeros((2,5))

In [8]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
##Create an array of 1s

c=np.ones((2,4))

In [10]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
##Create an identity matric
d=np.eye(2,5)

In [12]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [14]:
##Create a random array
e=np.random.random((2,5))

In [15]:
e

array([[0.00617272, 0.91323236, 0.59853027, 0.25382049, 0.90951194],
       [0.00692004, 0.69277094, 0.22923422, 0.00760023, 0.91881782]])

In [16]:
##Create a random integer array
f=np.random.randint(10,50,(3,4))

In [17]:
f

array([[32, 46, 31, 34],
       [12, 34, 14, 33],
       [16, 45, 30, 35]])

In [18]:
##Create an equidistance array
g=np.linspace(10,70,5)

In [19]:
g

array([10., 25., 40., 55., 70.])

In [20]:
## Create an array with user defined steps
h=np.arange(10,100,5)

In [21]:
h

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [22]:
## sum of 2 array

In [23]:
x=f=np.random.randint(10,50,(3,4))
y=f=np.random.randint(0,50,(3,4))

In [27]:
sum=x+y

In [28]:
sum

array([[31, 47, 78, 82],
       [24, 31, 60, 74],
       [71, 53, 20, 79]])

In [29]:
#mean
x.mean()

30.916666666666668

In [30]:
y.mean()

23.25

In [32]:
#max
x.max()

49

In [33]:
#Min
x.min()

12

In [7]:
l=[2,2,3,4]
l1=[1,2,4,3]


In [8]:
array=np.asarray([l,l1])

In [9]:
array

array([[2, 2, 3, 4],
       [1, 2, 4, 3]])

In [10]:
array.size

8

In [11]:
array.shape

(2, 4)

In [16]:
array

array([[2, 2, 3, 4],
       [1, 2, 4, 3]])

In [17]:
array[1]

array([1, 2, 4, 3])

In [18]:
array

array([[2, 2, 3, 4],
       [1, 2, 4, 3]])

In [19]:
array=np.random.randint(10,20,(2,5))

In [20]:
array

array([[18, 11, 10, 16, 14],
       [13, 18, 14, 14, 10]])

In [24]:
array[0,2]

10

In [25]:
array[0,2]=5

In [26]:
array

array([[18, 11,  5, 16, 14],
       [13, 18, 14, 14, 10]])

In [28]:
array[1:3,1:]

array([[18, 14, 14, 10]])

In [29]:
array<2

array([[False, False, False, False, False],
       [False, False, False, False, False]])