In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df=np.full((2,3),3)

In [6]:
df=np.random.randint(2,10,(3,4))

In [7]:
df

array([[9, 8, 7, 8],
       [8, 3, 9, 3],
       [6, 7, 6, 3]])

In [8]:
df1=pd.DataFrame(data=df,index=['Row1','Row2','Row3'],columns=['Name','Address','Phone','Location'])

In [9]:
df1

Name  Address  Phone  Location
Row1     9        8      7         8
Row2     8        3      9         3
Row3     6        7      6         3

In [9]:
df1.describe()

Name   Address     Phone  Location
count  3.000000  3.000000  3.000000  3.000000
mean   4.333333  7.000000  4.666667  6.666667
std    2.309401  1.732051  1.527525  2.081666
min    3.000000  6.000000  3.000000  5.000000
25%    3.000000  6.000000  4.000000  5.500000
50%    3.000000  6.000000  5.000000  6.000000
75%    5.000000  7.500000  5.500000  7.500000
max    7.000000  9.000000  6.000000  9.000000

In [10]:
df1.head()

Name  Address  Phone  Location
Row1     3        6      3         9
Row2     7        9      5         6
Row3     3        6      6         5

In [11]:
df1.tail()

Name  Address  Phone  Location
Row1     3        6      3         9
Row2     7        9      5         6
Row3     3        6      6         5

In [12]:
type(df)

numpy.ndarray

In [13]:
type(df1)

pandas.core.frame.DataFrame

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      3 non-null      int64
 1   Address   3 non-null      int64
 2   Phone     3 non-null      int64
 3   Location  3 non-null      int64
dtypes: int64(4)
memory usage: 120.0+ bytes


In [15]:
##Indexing
df1[['Name','Address']]

Name  Address
Row1     3        6
Row2     7        9
Row3     3        6

In [16]:
array_np=np.linspace(1,10,20)

In [17]:
array_np

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
array_np=array_np.reshape(5,4)

In [19]:
data_frame=pd.DataFrame(data=array_np,index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])

In [20]:
data_frame

col1      col2      col3       col4
row1  1.000000  1.473684  1.947368   2.421053
row2  2.894737  3.368421  3.842105   4.315789
row3  4.789474  5.263158  5.736842   6.210526
row4  6.684211  7.157895  7.631579   8.105263
row5  8.578947  9.052632  9.526316  10.000000

In [21]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    5 non-null      float64
 1   col2    5 non-null      float64
 2   col3    5 non-null      float64
 3   col4    5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [22]:
data_frame.head()

col1      col2      col3       col4
row1  1.000000  1.473684  1.947368   2.421053
row2  2.894737  3.368421  3.842105   4.315789
row3  4.789474  5.263158  5.736842   6.210526
row4  6.684211  7.157895  7.631579   8.105263
row5  8.578947  9.052632  9.526316  10.000000

In [23]:
data_frame.describe()

col1      col2      col3       col4
count  5.000000  5.000000  5.000000   5.000000
mean   4.789474  5.263158  5.736842   6.210526
std    2.995842  2.995842  2.995842   2.995842
min    1.000000  1.473684  1.947368   2.421053
25%    2.894737  3.368421  3.842105   4.315789
50%    4.789474  5.263158  5.736842   6.210526
75%    6.684211  7.157895  7.631579   8.105263
max    8.578947  9.052632  9.526316  10.000000

In [24]:
data_frame.min()


col1    1.000000
col2    1.473684
col3    1.947368
col4    2.421053
dtype: float64

In [25]:
data_frame.max()

col1     8.578947
col2     9.052632
col3     9.526316
col4    10.000000
dtype: float64

In [39]:
data_frame.mean()

col1    4.789474
col2    5.263158
col3    5.736842
col4    6.210526
dtype: float64

In [28]:
data_frame.median()

col1    4.789474
col2    5.263158
col3    5.736842
col4    6.210526
dtype: float64

In [27]:
data_frame.isnull()

col1   col2   col3   col4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [29]:
data_frame.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [31]:
data_frame[['col1','col2']]

col1      col2
row1  1.000000  1.473684
row2  2.894737  3.368421
row3  4.789474  5.263158
row4  6.684211  7.157895
row5  8.578947  9.052632

In [34]:
data_frame.loc[['row2','row3']]

col1      col2      col3      col4
row2  2.894737  3.368421  3.842105  4.315789
row3  4.789474  5.263158  5.736842  6.210526

In [35]:
data_frame.iloc[1:2,1:2]

col2
row2  3.368421

In [36]:
np.asarray(data_frame)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [38]:
data_frame.isnull().sum()

col1    0
col2    0
col3    0
col4    0
dtype: int64

In [40]:
data_frame.value_counts()

col1      col2      col3      col4     
1.000000  1.473684  1.947368  2.421053     1
2.894737  3.368421  3.842105  4.315789     1
4.789474  5.263158  5.736842  6.210526     1
6.684211  7.157895  7.631579  8.105263     1
8.578947  9.052632  9.526316  10.000000    1
dtype: int64

In [41]:
data_frame['col1'].unique()

array([1.        , 2.89473684, 4.78947368, 6.68421053, 8.57894737])

In [42]:
mar=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Complete-Feature-Engineering/master/mercedesbenz.csv')

In [44]:
mar.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [45]:
mar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [46]:
mar.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [49]:
mar.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [50]:
mar.mean()

/tmp/ipykernel_77/1085728974.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mar.mean()


ID      4205.960798
y        100.669318
X10        0.013305
X11        0.000000
X12        0.075077
           ...     
X380       0.008078
X382       0.007603
X383       0.001663
X384       0.000475
X385       0.001426
Length: 370, dtype: float64

In [51]:
mar.median()

/tmp/ipykernel_77/3922215925.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mar.median()


ID      4220.00
y         99.15
X10        0.00
X11        0.00
X12        0.00
         ...   
X380       0.00
X382       0.00
X383       0.00
X384       0.00
X385       0.00
Length: 370, dtype: float64

In [52]:
mar.sum()

ID                                               17702889
y                                               423717.16
X0      kkazazaztalowjhalsalonalayfnftxxyoajtfxazwxoak...
X1      vtwtvbrlsbrrbrslraacasaarbrslaasbvebssblvvslha...
X2      atavnnneeasasaqreaieasakeasmakmasamakmasasasma...
                              ...                        
X380                                                   34
X382                                                   32
X383                                                    7
X384                                                    2
X385                                                    6
Length: 378, dtype: object

In [53]:
mar.tail()

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[5 rows x 378 columns]

In [55]:
mar.iloc[0:5,0:8]

ID       y  X0 X1  X2 X3 X4 X5
0   0  130.81   k  v  at  a  d  u
1   6   88.53   k  t  av  e  d  y
2   7   76.26  az  w   n  c  d  x
3   9   80.62  az  t   n  f  d  x
4  13   78.02  az  v   n  f  d  h

In [68]:
mar.loc[

ID         13
y       78.02
X0         az
X1          v
X2          n
        ...  
X380        0
X382        0
X383        0
X384        0
X385        0
Name: 4, Length: 378, dtype: object

In [70]:
np.asarray(mar.iloc[0:4,0:8])

array([[0, 130.81, 'k', 'v', 'at', 'a', 'd', 'u'],
       [6, 88.53, 'k', 't', 'av', 'e', 'd', 'y'],
       [7, 76.26, 'az', 'w', 'n', 'c', 'd', 'x'],
       [9, 80.62, 'az', 't', 'n', 'f', 'd', 'x']], dtype=object)

In [75]:
from io import StringIO

In [81]:
data=('1,2,3','\n1,2,3')

In [82]:
StringIO(data)

TypeError: initial_value must be str or None, not tuple

In [127]:
##Using Specific Columns




mar1=pd.read_csv('https://raw.githubusercontent.com/krishnaik06/Complete-Feature-Engineering/master/mercedesbenz.csv',usecols=['X0','X1','X2','X3','X4','X5','X6','X8'])

In [94]:
mar1

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [96]:
##To another CSV File
mar1.to_csv('test.csv')

In [97]:
##To another CSV File without indexes
mar1.to_csv('test.csv',index=False)

In [98]:
mar1

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [99]:
mar1['X0'][0:3]

0     k
1     k
2    az
Name: X0, dtype: object

In [100]:
string=('a,b,c,\n''1,2,3')

In [101]:
##Changing Datatype
df_2=pd.read_csv(StringIO(string),dtype={'a':'int','b':'float','c':'float'})

In [102]:
df_2

a    b    c  Unnamed: 3
0  1  2.0  3.0         NaN

In [104]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   a           1 non-null      int64  
 1   b           1 non-null      float64
 2   c           1 non-null      float64
 3   Unnamed: 3  0 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 160.0 bytes


In [110]:
df_2=pd.read_csv(StringIO(string),dtype={'a':'int','b':'float','c':'float'},index_col=0)

In [111]:
df_2

b    c  Unnamed: 3
a                      
1  2.0  3.0         NaN

In [112]:
mar

ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0   
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0   
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0   
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0   
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0   
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...   
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0   
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0   
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0   
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0   
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     1     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4204     0     0     0     0     0     0  
4205     0     0     0     0     0     0  
4206     0     0     0     0     0     0  
4207     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[4209 rows x 378 columns]

In [119]:
mar['X376'].describe()

count    4209.000000
mean        0.057258
std         0.232363
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: X376, dtype: float64

In [15]:
## Working with a JSON File

In [29]:
str='{"fruit": "Apple","size": "Large","color": "Red"}'

In [33]:
type(str)

str

In [42]:
pd.read_json(str,orient='index')

0
fruit  Apple
size   Large
color    Red

In [45]:
str2='{"quiz": {"sport": { "q1": { "question": "Which one is correct team name in NBA?","options": [ "New York Bulls", "Los Angeles Kings", "Golden State Warriros","Huston Rocket" ], "answer": "Huston Rocket" } },"maths": { "q1": {  "question": "5 + 7 = ?", "options": ["10","11", "12","13"],"answer": "12"},"q2": {"question": "12 - 8 = ?","options": ["1","2","3","4"],"answer": "4"}}}}'

In [51]:
pd.read_json(str2)

quiz
maths  {'q1': {'question': '5 + 7 = ?', 'options': ['...
sport  {'q1': {'question': 'Which one is correct team...

In [72]:
str3=[{"id":"12345","name":"John Doe","contact":{"email":"john.doe@example.com","phone":{"home":"555-1234","work":"555-5678"}},"address":[{"type":"home","line1":"123 Elm St","line2":"","city":"Somewhere","state":"CA","zip":"90210"},{"type":"work","line1":"456 Oak St","line2":"Suite 789","city":"Anywhere","state":"CA","zip":"90120"}],"orders":[{"order_id":"001","date":"2024-01-15","items":[{"item_id":"A1","name":"Widget","quantity":4},{"item_id":"B2","name":"Gadget","quantity":2}]},{"order_id":"002","date":"2024-02-20","items":[{"item_id":"C3","name":"Doodad","quantity":1}]}]}]


In [83]:
df=pd.json_normalize(str3)

In [59]:
df

0
id                                                   12345
name                                              John Doe
contact  {'email': 'john.doe@example.com', 'phone': {'h...
address  [{'type': 'home', 'line1': '123 Elm St', 'line...
orders   [{'order_id': '001', 'date': '2024-01-15', 'it...

In [86]:
data=[
    {
        "state": "Florida",
        "shortname": "FL",
        "info": {"governor": "Rick Scott"},
        "counties": [
            {"name": "Dade", "population": 12345},
            {"name": "Broward", "population": 40000},
            {"name": "Palm Beach", "population": 60000},
        ],
    },
    {
        "state": "Ohio",
        "shortname": "OH",
        "info": {"governor": "John Kasich"},
        "counties": [
            {"name": "Summit", "population": 1234},
            {"name": "Cuyahoga", "population": 1337},
        ],
    },
]


In [111]:
pd.json_normalize(data,'counties',['state','shortname',['info','governor']])

name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

In [9]:
##PANDAS and HTML

df=pd.read_html("https://en.wikipedia.org/wiki/List_of_Indian_states_by_life_expectancy_at_birth",match='on the whole')

In [18]:
type(df[0])

pandas.core.frame.DataFrame

In [19]:
df=pd.DataFrame(df[0])

In [27]:
df.describe()

on the whole                            urban                        \
           overall      males    females    overall      males    females   
count    23.000000  23.000000  23.000000  23.000000  23.000000  23.000000   
mean     70.700000  69.069565  72.486957  73.204348  71.830435  74.760870   
std       2.708237   2.524684   3.273767   2.394402   2.153102   3.099375   
min      65.100000  63.500000  66.700000  68.000000  66.700000  69.300000   
25%      69.550000  67.400000  70.450000  72.100000  70.900000  72.800000   
50%      70.300000  69.100000  72.200000  72.700000  71.900000  74.500000   
75%      72.700000  70.900000  74.400000  74.650000  73.350000  76.950000   
max      75.800000  74.100000  78.000000  78.100000  76.000000  81.000000   

           rural             
         overall    females  
count  23.000000  23.000000  
mean   69.600000  71.595652  
std     2.681418   3.286678  
min    64.300000  65.900000  
25%    68.400000  69.500000  
50%    69.200000  71.600000  
75%    71.000000  73.050000  
max    75.200000  78.100000

In [29]:
## Converting to HTML

df.to_html('demo.html')